//
//  LocalizationStrings.swift
//  CarAssistant
//
//  Created on 10.11.2024.
//

import Foundation

/// Словари локализации для всех поддерживаемых языков
struct LocalizationStrings {
    
    // MARK: - English
    
    static let english: [String: String] = [
        // Common
        "common.ok": "OK",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.add": "Add",
        "common.close": "Close",
        "common.back": "Back",
        "common.next": "Next",
        "common.done": "Done",
        
        // Tab Bar
        "tabbar.chats": "Chats",
        "tabbar.maintenance": "Maintenance",
        "tabbar.profile": "Profile",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "Your car assistant",
        "welcome.login": "Login",
        "welcome.register": "Register",
        
        // Settings
        "settings.profile": "Profile",
        "settings.myCars": "My Cars",
        "settings.noCars": "No saved cars",
        "settings.addCar": "Add Car",
        "settings.geolocation": "Geolocation",
        "settings.autoDetermined": "Automatically determined",
        "settings.determineLocation": "Determine location",
        "settings.determining": "Determining...",
        "settings.appearance": "Appearance",
        "settings.theme": "Theme",
        "settings.lightTheme": "Light",
        "settings.darkTheme": "Dark",
        "settings.language": "Language",
        "settings.account": "Account",
        "settings.logout": "Logout",
        
        // Chat
        "chat.startDialog": "Start a dialogue with the AI assistant",
        "chat.writeMessage": "Write a message...",
        "chat.generalQuestion": "General Question",
        "chat.checkEngine": "Check Engine",
        "chat.battery": "Battery",
        "chat.brakeSystem": "Brake System",
        "chat.engine": "Engine",
        "chat.transmission": "Transmission",
        "chat.suspension": "Suspension",
        "chat.electrical": "Electrical",
        "chat.acSystem": "AC System",
        "chat.tires": "Tires",
        "chat.chats": "Chats",
        
        // Maintenance
        "maintenance.title": "Maintenance",
        "maintenance.noRecords": "No maintenance records",
        "maintenance.addMaintenance": "Add Maintenance",
        "maintenance.upcomingServices": "Upcoming Services",
        "maintenance.history": "History",
        "maintenance.addFirstRecord": "Add first maintenance record",
        
        // Car Input
        "carInput.addCar": "Add Car",
        "carInput.brand": "Brand",
        "carInput.model": "Model",
        "carInput.year": "Year",
        "carInput.engine": "Engine",
        "carInput.selectEngine": "Select engine",
        "carInput.additionalParams": "Additional Parameters",
        "carInput.fuelType": "Fuel Type",
        "carInput.driveType": "Drive Type",
        "carInput.transmission": "Transmission",
        "carInput.notSpecified": "Not specified",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (optional)",
        "carInput.additionalInfo": "Additional Information",
        "carInput.notes": "Notes, features, wishes...",
        "carInput.addPhoto": "Add Photo",
        "carInput.selectSource": "Select Source",
        "carInput.camera": "Camera",
        "carInput.gallery": "Gallery",
        "carInput.enterBrandFirst": "Enter brand first",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "Edit Maintenance",
        "maintenanceInput.dateAndMileage": "Date and Mileage",
        "maintenanceInput.maintenanceDate": "Maintenance Date",
        "maintenanceInput.plannedDate": "Planned Work Date",
        "maintenanceInput.workDate": "Work Date",
        "maintenanceInput.mileage": "Mileage (km)",
        "maintenanceInput.works": "Works",
        "maintenanceInput.selectType": "Select type",
        "maintenanceInput.description": "Description",
        "maintenanceInput.worksDescription": "Work description",
        "maintenanceInput.performedWorks": "Performed Works",
        "maintenanceInput.performedWorksList": "List of performed works",
        "maintenanceInput.document": "Document (receipt/work order)",
        "maintenanceInput.attachPhoto": "Attach Photo",
        "maintenanceInput.deletePhoto": "Delete Photo",
        "maintenanceInput.analyzing": "Analyzing...",
        "maintenanceInput.textRecognized": "Text recognized",
        "maintenanceInput.recognizedText": "Recognized Text",
        "maintenanceInput.useRecognizedText": "Use Recognized Text",
        "maintenanceInput.plannedWork": "Planned Work",
        "maintenanceInput.addType": "Add",
        "maintenanceInput.addTypeName": "Type name",
        "maintenanceInput.addMaintenanceType": "Add Maintenance Type",
        "maintenanceInput.addRepairType": "Add Repair Type",
        "maintenanceInput.enterMaintenanceType": "Enter new maintenance type name",
        "maintenanceInput.enterRepairType": "Enter new repair type name",
        "maintenanceInput.describeWorkType": "Describe work type",
        "maintenanceInput.addWorkType": "Add work type",
        "maintenanceInput.enterWorkTypeName": "Enter work type name",
        "maintenanceInput.overdue": "Overdue by",
        "maintenanceInput.days": "days",
        "maintenanceInput.in": "In",
        "maintenanceInput.mileageLabel": "Mileage:",
        "maintenanceInput.documentAttached": "Document attached",
        
        // Car Management
        "carInput.editCar": "Edit Car",
        "carInput.myCars": "My Cars",
        "carInput.addFirstCar": "Add first car",
        
        // Maintenance Types
        "maintenanceType.maintenance": "Maintenance",
        "maintenanceType.repair": "Repair",
        "maintenanceType.replacement": "Replacement",
        "maintenanceType.other": "Other",
        "maintenanceType.plannedMaintenance": "Planned Maintenance",
        "maintenanceType.oilChange": "Oil Change",
        "maintenanceType.filterReplacement": "Filter Replacement",
        "maintenanceType.brakeReplacement": "Brake Replacement",
        "maintenanceType.tireReplacement": "Tire Replacement",
        "maintenanceType.diagnostics": "Diagnostics",
        "maintenanceType.engineRepair": "Engine Repair",
        "maintenanceType.transmissionRepair": "Transmission Repair",
        "maintenanceType.suspensionRepair": "Suspension Repair",
        "maintenanceType.brakeRepair": "Brake Repair",
        "maintenanceType.bodyRepair": "Body Repair",
        "maintenanceType.electricalRepair": "Electrical Repair",
        
        // Fuel Types
        "fuelType.gasoline": "Gasoline",
        "fuelType.diesel": "Diesel",
        "fuelType.hybrid": "Hybrid",
        "fuelType.electric": "Electric",
        "fuelType.gas": "Gas",
        "fuelType.gasGasoline": "Gas/Gasoline",
        
        // Drive Types
        "driveType.front": "Front",
        "driveType.rear": "Rear",
        "driveType.full": "Full",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "Manual",
        "transmission.automatic": "Automatic",
        "transmission.robot": "Robot",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "Take Photo",
        "photo.chooseFromGallery": "Choose from Gallery"
    ]
    
    // MARK: - Spanish
    
    static let spanish: [String: String] = [
        // Common
        "common.ok": "OK",
        "common.cancel": "Cancelar",
        "common.save": "Guardar",
        "common.delete": "Eliminar",
        "common.edit": "Editar",
        "common.add": "Agregar",
        "common.close": "Cerrar",
        "common.back": "Atrás",
        "common.next": "Siguiente",
        "common.done": "Hecho",
        
        // Tab Bar
        "tabbar.chats": "Chats",
        "tabbar.maintenance": "Mantenimiento",
        "tabbar.profile": "Perfil",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "Tu asistente de automóviles",
        "welcome.login": "Iniciar sesión",
        "welcome.register": "Registrarse",
        
        // Settings
        "settings.profile": "Perfil",
        "settings.myCars": "Mis Autos",
        "settings.noCars": "No hay autos guardados",
        "settings.addCar": "Agregar Auto",
        "settings.geolocation": "Geolocalización",
        "settings.autoDetermined": "Determinado automáticamente",
        "settings.determineLocation": "Determinar ubicación",
        "settings.determining": "Determinando...",
        "settings.appearance": "Apariencia",
        "settings.theme": "Tema",
        "settings.lightTheme": "Claro",
        "settings.darkTheme": "Oscuro",
        "settings.language": "Idioma",
        "settings.account": "Cuenta",
        "settings.logout": "Cerrar sesión",
        
        // Chat
        "chat.startDialog": "Inicia un diálogo con el asistente de IA",
        "chat.writeMessage": "Escribe un mensaje...",
        "chat.generalQuestion": "Pregunta General",
        "chat.checkEngine": "Motor de Verificación",
        "chat.battery": "Batería",
        "chat.brakeSystem": "Sistema de Frenos",
        "chat.engine": "Motor",
        "chat.transmission": "Transmisión",
        "chat.suspension": "Suspensión",
        "chat.electrical": "Eléctrico",
        "chat.acSystem": "Sistema de Aire Acondicionado",
        "chat.tires": "Neumáticos",
        "chat.chats": "Chats",
        
        // Maintenance
        "maintenance.title": "Mantenimiento",
        "maintenance.noRecords": "No hay registros de mantenimiento",
        "maintenance.addMaintenance": "Agregar Mantenimiento",
        "maintenance.upcomingServices": "Servicios Próximos",
        "maintenance.history": "Historial",
        "maintenance.addFirstRecord": "Agregar primer registro de mantenimiento",
        
        // Car Input
        "carInput.addCar": "Agregar Auto",
        "carInput.brand": "Marca",
        "carInput.model": "Modelo",
        "carInput.year": "Año",
        "carInput.engine": "Motor",
        "carInput.selectEngine": "Seleccionar motor",
        "carInput.additionalParams": "Parámetros Adicionales",
        "carInput.fuelType": "Tipo de Combustible",
        "carInput.driveType": "Tipo de Tracción",
        "carInput.transmission": "Transmisión",
        "carInput.notSpecified": "No especificado",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (opcional)",
        "carInput.additionalInfo": "Información Adicional",
        "carInput.notes": "Notas, características, deseos...",
        "carInput.addPhoto": "Agregar Foto",
        "carInput.selectSource": "Seleccionar Fuente",
        "carInput.camera": "Cámara",
        "carInput.gallery": "Galería",
        "carInput.enterBrandFirst": "Ingrese la marca primero",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "Editar Mantenimiento",
        "maintenanceInput.dateAndMileage": "Fecha y Kilometraje",
        "maintenanceInput.maintenanceDate": "Fecha de Mantenimiento",
        "maintenanceInput.plannedDate": "Fecha de Trabajo Planificado",
        "maintenanceInput.workDate": "Fecha de Trabajo",
        "maintenanceInput.mileage": "Kilometraje (km)",
        "maintenanceInput.works": "Trabajos",
        "maintenanceInput.selectType": "Seleccionar tipo",
        "maintenanceInput.description": "Descripción",
        "maintenanceInput.worksDescription": "Descripción del trabajo",
        "maintenanceInput.performedWorks": "Trabajos Realizados",
        "maintenanceInput.performedWorksList": "Lista de trabajos realizados",
        "maintenanceInput.document": "Documento (recibo/orden de trabajo)",
        "maintenanceInput.attachPhoto": "Adjuntar Foto",
        "maintenanceInput.deletePhoto": "Eliminar Foto",
        "maintenanceInput.analyzing": "Analizando...",
        "maintenanceInput.textRecognized": "Texto reconocido",
        "maintenanceInput.recognizedText": "Texto Reconocido",
        "maintenanceInput.useRecognizedText": "Usar Texto Reconocido",
        "maintenanceInput.plannedWork": "Trabajo Planificado",
        "maintenanceInput.addType": "Agregar",
        "maintenanceInput.addTypeName": "Nombre del tipo",
        "maintenanceInput.addMaintenanceType": "Agregar Tipo de Mantenimiento",
        "maintenanceInput.addRepairType": "Agregar Tipo de Reparación",
        "maintenanceInput.enterMaintenanceType": "Ingrese el nombre del nuevo tipo de mantenimiento",
        "maintenanceInput.enterRepairType": "Ingrese el nombre del nuevo tipo de reparación",
        "maintenanceInput.describeWorkType": "Describir tipo de trabajo",
        "maintenanceInput.addWorkType": "Agregar tipo de trabajo",
        "maintenanceInput.enterWorkTypeName": "Ingrese el nombre del tipo de trabajo",
        "maintenanceInput.overdue": "Vencido por",
        "maintenanceInput.days": "días",
        "maintenanceInput.in": "En",
        "maintenanceInput.mileageLabel": "Kilometraje:",
        "maintenanceInput.documentAttached": "Documento adjunto",
        
        // Car Management
        "carInput.editCar": "Editar Auto",
        "carInput.myCars": "Mis Autos",
        "carInput.addFirstCar": "Agregar primer auto",
        
        // Maintenance Types
        "maintenanceType.maintenance": "Mantenimiento",
        "maintenanceType.repair": "Reparación",
        "maintenanceType.replacement": "Reemplazo",
        "maintenanceType.other": "Otro",
        "maintenanceType.plannedMaintenance": "Mantenimiento Planificado",
        "maintenanceType.oilChange": "Cambio de Aceite",
        "maintenanceType.filterReplacement": "Reemplazo de Filtros",
        "maintenanceType.brakeReplacement": "Reemplazo de Frenos",
        "maintenanceType.tireReplacement": "Reemplazo de Neumáticos",
        "maintenanceType.diagnostics": "Diagnóstico",
        "maintenanceType.engineRepair": "Reparación de Motor",
        "maintenanceType.transmissionRepair": "Reparación de Transmisión",
        "maintenanceType.suspensionRepair": "Reparación de Suspensión",
        "maintenanceType.brakeRepair": "Reparación de Frenos",
        "maintenanceType.bodyRepair": "Reparación de Carrocería",
        "maintenanceType.electricalRepair": "Reparación Eléctrica",
        
        // Fuel Types
        "fuelType.gasoline": "Gasolina",
        "fuelType.diesel": "Diésel",
        "fuelType.hybrid": "Híbrido",
        "fuelType.electric": "Eléctrico",
        "fuelType.gas": "Gas",
        "fuelType.gasGasoline": "Gas/Gasolina",
        
        // Drive Types
        "driveType.front": "Delantero",
        "driveType.rear": "Trasero",
        "driveType.full": "Completo",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "Manual",
        "transmission.automatic": "Automática",
        "transmission.robot": "Robot",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "Tomar Foto",
        "photo.chooseFromGallery": "Elegir de la Galería"
    ]
    
    // MARK: - Hindi
    
    static let hindi: [String: String] = [
        // Common
        "common.ok": "ठीक है",
        "common.cancel": "रद्द करें",
        "common.save": "सहेजें",
        "common.delete": "हटाएं",
        "common.edit": "संपादित करें",
        "common.add": "जोड़ें",
        "common.close": "बंद करें",
        "common.back": "वापस",
        "common.next": "अगला",
        "common.done": "पूर्ण",
        
        // Tab Bar
        "tabbar.chats": "चैट",
        "tabbar.maintenance": "रखरखाव",
        "tabbar.profile": "प्रोफ़ाइल",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "आपका कार सहायक",
        "welcome.login": "लॉगिन",
        "welcome.register": "पंजीकरण",
        
        // Settings
        "settings.profile": "प्रोफ़ाइल",
        "settings.myCars": "मेरी कारें",
        "settings.noCars": "कोई सहेजी गई कार नहीं",
        "settings.addCar": "कार जोड़ें",
        "settings.geolocation": "जियोलोकेशन",
        "settings.autoDetermined": "स्वचालित रूप से निर्धारित",
        "settings.determineLocation": "स्थान निर्धारित करें",
        "settings.determining": "निर्धारित कर रहे हैं...",
        "settings.appearance": "दिखावट",
        "settings.theme": "थीम",
        "settings.lightTheme": "हल्का",
        "settings.darkTheme": "गहरा",
        "settings.language": "भाषा",
        "settings.account": "खाता",
        "settings.logout": "लॉगआउट",
        
        // Chat
        "chat.startDialog": "AI सहायक के साथ संवाद शुरू करें",
        "chat.writeMessage": "एक संदेश लिखें...",
        "chat.generalQuestion": "सामान्य प्रश्न",
        "chat.checkEngine": "इंजन जांच",
        "chat.battery": "बैटरी",
        "chat.brakeSystem": "ब्रेक सिस्टम",
        "chat.engine": "इंजन",
        "chat.transmission": "ट्रांसमिशन",
        "chat.suspension": "निलंबन",
        "chat.electrical": "विद्युत",
        "chat.acSystem": "AC सिस्टम",
        "chat.tires": "टायर",
        "chat.chats": "चैट",
        
        // Maintenance
        "maintenance.title": "रखरखाव",
        "maintenance.noRecords": "कोई रखरखाव रिकॉर्ड नहीं",
        "maintenance.addMaintenance": "रखरखाव जोड़ें",
        "maintenance.upcomingServices": "आगामी सेवाएं",
        "maintenance.history": "इतिहास",
        "maintenance.addFirstRecord": "पहला रखरखाव रिकॉर्ड जोड़ें",
        
        // Car Input
        "carInput.addCar": "कार जोड़ें",
        "carInput.brand": "ब्रांड",
        "carInput.model": "मॉडल",
        "carInput.year": "वर्ष",
        "carInput.engine": "इंजन",
        "carInput.selectEngine": "इंजन चुनें",
        "carInput.additionalParams": "अतिरिक्त पैरामीटर",
        "carInput.fuelType": "ईंधन प्रकार",
        "carInput.driveType": "ड्राइव प्रकार",
        "carInput.transmission": "ट्रांसमिशन",
        "carInput.notSpecified": "निर्दिष्ट नहीं",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (वैकल्पिक)",
        "carInput.additionalInfo": "अतिरिक्त जानकारी",
        "carInput.notes": "नोट्स, विशेषताएं, इच्छाएं...",
        "carInput.addPhoto": "फोटो जोड़ें",
        "carInput.selectSource": "स्रोत चुनें",
        "carInput.camera": "कैमरा",
        "carInput.gallery": "गैलरी",
        "carInput.enterBrandFirst": "पहले ब्रांड दर्ज करें",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "रखरखाव संपादित करें",
        "maintenanceInput.dateAndMileage": "तारीख और माइलेज",
        "maintenanceInput.maintenanceDate": "रखरखाव तारीख",
        "maintenanceInput.plannedDate": "नियोजित कार्य तारीख",
        "maintenanceInput.workDate": "कार्य तारीख",
        "maintenanceInput.mileage": "माइलेज (किमी)",
        "maintenanceInput.works": "कार्य",
        "maintenanceInput.selectType": "प्रकार चुनें",
        "maintenanceInput.description": "विवरण",
        "maintenanceInput.worksDescription": "कार्य विवरण",
        "maintenanceInput.performedWorks": "किए गए कार्य",
        "maintenanceInput.performedWorksList": "किए गए कार्यों की सूची",
        "maintenanceInput.document": "दस्तावेज़ (रसीद/कार्य आदेश)",
        "maintenanceInput.attachPhoto": "फोटो संलग्न करें",
        "maintenanceInput.deletePhoto": "फोटो हटाएं",
        "maintenanceInput.analyzing": "विश्लेषण...",
        "maintenanceInput.textRecognized": "पाठ पहचाना गया",
        "maintenanceInput.recognizedText": "पहचाना गया पाठ",
        "maintenanceInput.useRecognizedText": "पहचाने गए पाठ का उपयोग करें",
        "maintenanceInput.plannedWork": "नियोजित कार्य",
        "maintenanceInput.addType": "जोड़ें",
        "maintenanceInput.addTypeName": "प्रकार का नाम",
        "maintenanceInput.addMaintenanceType": "रखरखाव प्रकार जोड़ें",
        "maintenanceInput.addRepairType": "मरम्मत प्रकार जोड़ें",
        "maintenanceInput.enterMaintenanceType": "नए रखरखाव प्रकार का नाम दर्ज करें",
        "maintenanceInput.enterRepairType": "नए मरम्मत प्रकार का नाम दर्ज करें",
        "maintenanceInput.describeWorkType": "कार्य प्रकार का वर्णन करें",
        "maintenanceInput.addWorkType": "कार्य प्रकार जोड़ें",
        "maintenanceInput.enterWorkTypeName": "कार्य प्रकार का नाम दर्ज करें",
        "maintenanceInput.overdue": "समय सीमा समाप्त",
        "maintenanceInput.days": "दिन",
        "maintenanceInput.in": "में",
        "maintenanceInput.mileageLabel": "माइलेज:",
        "maintenanceInput.documentAttached": "दस्तावेज़ संलग्न",
        
        // Car Management
        "carInput.editCar": "कार संपादित करें",
        "carInput.myCars": "मेरी कारें",
        "carInput.addFirstCar": "पहली कार जोड़ें",
        
        // Maintenance Types
        "maintenanceType.maintenance": "रखरखाव",
        "maintenanceType.repair": "मरम्मत",
        "maintenanceType.replacement": "प्रतिस्थापन",
        "maintenanceType.other": "अन्य",
        "maintenanceType.plannedMaintenance": "नियोजित रखरखाव",
        "maintenanceType.oilChange": "तेल परिवर्तन",
        "maintenanceType.filterReplacement": "फ़िल्टर प्रतिस्थापन",
        "maintenanceType.brakeReplacement": "ब्रेक प्रतिस्थापन",
        "maintenanceType.tireReplacement": "टायर प्रतिस्थापन",
        "maintenanceType.diagnostics": "निदान",
        "maintenanceType.engineRepair": "इंजन मरम्मत",
        "maintenanceType.transmissionRepair": "ट्रांसमिशन मरम्मत",
        "maintenanceType.suspensionRepair": "निलंबन मरम्मत",
        "maintenanceType.brakeRepair": "ब्रेक मरम्मत",
        "maintenanceType.bodyRepair": "बॉडी मरम्मत",
        "maintenanceType.electricalRepair": "विद्युत मरम्मत",
        
        // Fuel Types
        "fuelType.gasoline": "पेट्रोल",
        "fuelType.diesel": "डीजल",
        "fuelType.hybrid": "हाइब्रिड",
        "fuelType.electric": "विद्युत",
        "fuelType.gas": "गैस",
        "fuelType.gasGasoline": "गैस/पेट्रोल",
        
        // Drive Types
        "driveType.front": "सामने",
        "driveType.rear": "पीछे",
        "driveType.full": "पूर्ण",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "मैनुअल",
        "transmission.automatic": "स्वचालित",
        "transmission.robot": "रोबोट",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "फोटो लें",
        "photo.chooseFromGallery": "गैलरी से चुनें"
    ]
    
    // MARK: - French
    
    static let french: [String: String] = [
        // Common
        "common.ok": "OK",
        "common.cancel": "Annuler",
        "common.save": "Enregistrer",
        "common.delete": "Supprimer",
        "common.edit": "Modifier",
        "common.add": "Ajouter",
        "common.close": "Fermer",
        "common.back": "Retour",
        "common.next": "Suivant",
        "common.done": "Terminé",
        
        // Tab Bar
        "tabbar.chats": "Chats",
        "tabbar.maintenance": "Entretien",
        "tabbar.profile": "Profil",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "Votre assistant automobile",
        "welcome.login": "Connexion",
        "welcome.register": "S'inscrire",
        
        // Settings
        "settings.profile": "Profil",
        "settings.myCars": "Mes Voitures",
        "settings.noCars": "Aucune voiture enregistrée",
        "settings.addCar": "Ajouter une Voiture",
        "settings.geolocation": "Géolocalisation",
        "settings.autoDetermined": "Déterminé automatiquement",
        "settings.determineLocation": "Déterminer l'emplacement",
        "settings.determining": "Détermination...",
        "settings.appearance": "Apparence",
        "settings.theme": "Thème",
        "settings.lightTheme": "Clair",
        "settings.darkTheme": "Sombre",
        "settings.language": "Langue",
        "settings.account": "Compte",
        "settings.logout": "Déconnexion",
        
        // Chat
        "chat.startDialog": "Démarrer un dialogue avec l'assistant IA",
        "chat.writeMessage": "Écrire un message...",
        "chat.generalQuestion": "Question Générale",
        "chat.checkEngine": "Vérification Moteur",
        "chat.battery": "Batterie",
        "chat.brakeSystem": "Système de Freinage",
        "chat.engine": "Moteur",
        "chat.transmission": "Transmission",
        "chat.suspension": "Suspension",
        "chat.electrical": "Électrique",
        "chat.acSystem": "Système de Climatisation",
        "chat.tires": "Pneus",
        "chat.chats": "Chats",
        
        // Maintenance
        "maintenance.title": "Entretien",
        "maintenance.noRecords": "Aucun enregistrement d'entretien",
        "maintenance.addMaintenance": "Ajouter un Entretien",
        "maintenance.upcomingServices": "Services à Venir",
        "maintenance.history": "Historique",
        "maintenance.addFirstRecord": "Ajouter le premier enregistrement d'entretien",
        
        // Car Input
        "carInput.addCar": "Ajouter une Voiture",
        "carInput.brand": "Marque",
        "carInput.model": "Modèle",
        "carInput.year": "Année",
        "carInput.engine": "Moteur",
        "carInput.selectEngine": "Sélectionner le moteur",
        "carInput.additionalParams": "Paramètres Supplémentaires",
        "carInput.fuelType": "Type de Carburant",
        "carInput.driveType": "Type de Transmission",
        "carInput.transmission": "Transmission",
        "carInput.notSpecified": "Non spécifié",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (optionnel)",
        "carInput.additionalInfo": "Informations Supplémentaires",
        "carInput.notes": "Notes, caractéristiques, souhaits...",
        "carInput.addPhoto": "Ajouter une Photo",
        "carInput.selectSource": "Sélectionner la Source",
        "carInput.camera": "Caméra",
        "carInput.gallery": "Galerie",
        "carInput.enterBrandFirst": "Entrez d'abord la marque",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "Modifier l'Entretien",
        "maintenanceInput.dateAndMileage": "Date et Kilométrage",
        "maintenanceInput.maintenanceDate": "Date d'Entretien",
        "maintenanceInput.plannedDate": "Date de Travail Planifié",
        "maintenanceInput.workDate": "Date de Travail",
        "maintenanceInput.mileage": "Kilométrage (km)",
        "maintenanceInput.works": "Travaux",
        "maintenanceInput.selectType": "Sélectionner le type",
        "maintenanceInput.description": "Description",
        "maintenanceInput.worksDescription": "Description du travail",
        "maintenanceInput.performedWorks": "Travaux Effectués",
        "maintenanceInput.performedWorksList": "Liste des travaux effectués",
        "maintenanceInput.document": "Document (reçu/bon de travail)",
        "maintenanceInput.attachPhoto": "Joindre une Photo",
        "maintenanceInput.deletePhoto": "Supprimer la Photo",
        "maintenanceInput.analyzing": "Analyse...",
        "maintenanceInput.textRecognized": "Texte reconnu",
        "maintenanceInput.recognizedText": "Texte Reconnu",
        "maintenanceInput.useRecognizedText": "Utiliser le Texte Reconnu",
        "maintenanceInput.plannedWork": "Travail Planifié",
        "maintenanceInput.addType": "Ajouter",
        "maintenanceInput.addTypeName": "Nom du type",
        "maintenanceInput.addMaintenanceType": "Ajouter un Type d'Entretien",
        "maintenanceInput.addRepairType": "Ajouter un Type de Réparation",
        "maintenanceInput.enterMaintenanceType": "Entrez le nom du nouveau type d'entretien",
        "maintenanceInput.enterRepairType": "Entrez le nom du nouveau type de réparation",
        "maintenanceInput.describeWorkType": "Décrire le type de travail",
        "maintenanceInput.addWorkType": "Ajouter un type de travail",
        "maintenanceInput.enterWorkTypeName": "Entrez le nom du type de travail",
        "maintenanceInput.overdue": "En retard de",
        "maintenanceInput.days": "jours",
        "maintenanceInput.in": "Dans",
        "maintenanceInput.mileageLabel": "Kilométrage:",
        "maintenanceInput.documentAttached": "Document joint",
        
        // Car Management
        "carInput.editCar": "Modifier la Voiture",
        "carInput.myCars": "Mes Voitures",
        "carInput.addFirstCar": "Ajouter la première voiture",
        
        // Maintenance Types
        "maintenanceType.maintenance": "Entretien",
        "maintenanceType.repair": "Réparation",
        "maintenanceType.replacement": "Remplacement",
        "maintenanceType.other": "Autre",
        "maintenanceType.plannedMaintenance": "Entretien Planifié",
        "maintenanceType.oilChange": "Changement d'Huile",
        "maintenanceType.filterReplacement": "Remplacement de Filtres",
        "maintenanceType.brakeReplacement": "Remplacement de Freins",
        "maintenanceType.tireReplacement": "Remplacement de Pneus",
        "maintenanceType.diagnostics": "Diagnostic",
        "maintenanceType.engineRepair": "Réparation Moteur",
        "maintenanceType.transmissionRepair": "Réparation Transmission",
        "maintenanceType.suspensionRepair": "Réparation Suspension",
        "maintenanceType.brakeRepair": "Réparation Freins",
        "maintenanceType.bodyRepair": "Réparation Carrosserie",
        "maintenanceType.electricalRepair": "Réparation Électrique",
        
        // Fuel Types
        "fuelType.gasoline": "Essence",
        "fuelType.diesel": "Diesel",
        "fuelType.hybrid": "Hybride",
        "fuelType.electric": "Électrique",
        "fuelType.gas": "Gaz",
        "fuelType.gasGasoline": "Gaz/Essence",
        
        // Drive Types
        "driveType.front": "Avant",
        "driveType.rear": "Arrière",
        "driveType.full": "Intégral",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "Manuelle",
        "transmission.automatic": "Automatique",
        "transmission.robot": "Robot",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "Prendre une Photo",
        "photo.chooseFromGallery": "Choisir dans la Galerie"
    ]
    
    // MARK: - Arabic
    
    static let arabic: [String: String] = [
        // Common
        "common.ok": "موافق",
        "common.cancel": "إلغاء",
        "common.save": "حفظ",
        "common.delete": "حذف",
        "common.edit": "تعديل",
        "common.add": "إضافة",
        "common.close": "إغلاق",
        "common.back": "رجوع",
        "common.next": "التالي",
        "common.done": "تم",
        
        // Tab Bar
        "tabbar.chats": "المحادثات",
        "tabbar.maintenance": "الصيانة",
        "tabbar.profile": "الملف الشخصي",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "مساعدك للسيارات",
        "welcome.login": "تسجيل الدخول",
        "welcome.register": "التسجيل",
        
        // Settings
        "settings.profile": "الملف الشخصي",
        "settings.myCars": "سياراتي",
        "settings.noCars": "لا توجد سيارات محفوظة",
        "settings.addCar": "إضافة سيارة",
        "settings.geolocation": "الموقع الجغرافي",
        "settings.autoDetermined": "تم تحديده تلقائياً",
        "settings.determineLocation": "تحديد الموقع",
        "settings.determining": "جاري التحديد...",
        "settings.appearance": "المظهر",
        "settings.theme": "المظهر",
        "settings.lightTheme": "فاتح",
        "settings.darkTheme": "داكن",
        "settings.language": "اللغة",
        "settings.account": "الحساب",
        "settings.logout": "تسجيل الخروج",
        
        // Chat
        "chat.startDialog": "ابدأ حواراً مع مساعد الذكاء الاصطناعي",
        "chat.writeMessage": "اكتب رسالة...",
        "chat.generalQuestion": "سؤال عام",
        "chat.checkEngine": "فحص المحرك",
        "chat.battery": "البطارية",
        "chat.brakeSystem": "نظام الفرامل",
        "chat.engine": "المحرك",
        "chat.transmission": "ناقل الحركة",
        "chat.suspension": "التعليق",
        "chat.electrical": "الكهرباء",
        "chat.acSystem": "نظام التكييف",
        "chat.tires": "الإطارات",
        "chat.chats": "المحادثات",
        
        // Maintenance
        "maintenance.title": "الصيانة",
        "maintenance.noRecords": "لا توجد سجلات صيانة",
        "maintenance.addMaintenance": "إضافة صيانة",
        "maintenance.upcomingServices": "الخدمات القادمة",
        "maintenance.history": "السجل",
        "maintenance.addFirstRecord": "إضافة أول سجل صيانة",
        
        // Car Input
        "carInput.addCar": "إضافة سيارة",
        "carInput.brand": "العلامة التجارية",
        "carInput.model": "الموديل",
        "carInput.year": "السنة",
        "carInput.engine": "المحرك",
        "carInput.selectEngine": "اختر المحرك",
        "carInput.additionalParams": "معاملات إضافية",
        "carInput.fuelType": "نوع الوقود",
        "carInput.driveType": "نوع الدفع",
        "carInput.transmission": "ناقل الحركة",
        "carInput.notSpecified": "غير محدد",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (اختياري)",
        "carInput.additionalInfo": "معلومات إضافية",
        "carInput.notes": "ملاحظات، ميزات، رغبات...",
        "carInput.addPhoto": "إضافة صورة",
        "carInput.selectSource": "اختر المصدر",
        "carInput.camera": "الكاميرا",
        "carInput.gallery": "المعرض",
        "carInput.enterBrandFirst": "أدخل العلامة التجارية أولاً",
        "carInput.editCar": "تعديل السيارة",
        "carInput.myCars": "سياراتي",
        "carInput.addFirstCar": "إضافة أول سيارة",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "تعديل الصيانة",
        "maintenanceInput.dateAndMileage": "التاريخ والمسافة",
        "maintenanceInput.maintenanceDate": "تاريخ الصيانة",
        "maintenanceInput.plannedDate": "تاريخ العمل المخطط",
        "maintenanceInput.workDate": "تاريخ العمل",
        "maintenanceInput.mileage": "المسافة (كم)",
        "maintenanceInput.works": "الأعمال",
        "maintenanceInput.selectType": "اختر النوع",
        "maintenanceInput.description": "الوصف",
        "maintenanceInput.worksDescription": "وصف العمل",
        "maintenanceInput.performedWorks": "الأعمال المنجزة",
        "maintenanceInput.performedWorksList": "قائمة الأعمال المنجزة",
        "maintenanceInput.document": "المستند (إيصال/أمر عمل)",
        "maintenanceInput.attachPhoto": "إرفاق صورة",
        "maintenanceInput.deletePhoto": "حذف الصورة",
        "maintenanceInput.analyzing": "جاري التحليل...",
        "maintenanceInput.textRecognized": "تم التعرف على النص",
        "maintenanceInput.recognizedText": "النص المعروف",
        "maintenanceInput.useRecognizedText": "استخدام النص المعروف",
        "maintenanceInput.plannedWork": "عمل مخطط",
        "maintenanceInput.addType": "إضافة",
        "maintenanceInput.addTypeName": "اسم النوع",
        "maintenanceInput.addMaintenanceType": "إضافة نوع صيانة",
        "maintenanceInput.addRepairType": "إضافة نوع إصلاح",
        "maintenanceInput.enterMaintenanceType": "أدخل اسم نوع الصيانة الجديد",
        "maintenanceInput.enterRepairType": "أدخل اسم نوع الإصلاح الجديد",
        "maintenanceInput.describeWorkType": "وصف نوع العمل",
        "maintenanceInput.addWorkType": "إضافة نوع عمل",
        "maintenanceInput.enterWorkTypeName": "أدخل اسم نوع العمل",
        "maintenanceInput.overdue": "متأخر بـ",
        "maintenanceInput.days": "أيام",
        "maintenanceInput.in": "في",
        "maintenanceInput.mileageLabel": "المسافة:",
        "maintenanceInput.documentAttached": "مستند مرفق",
        
        // Maintenance Types
        "maintenanceType.maintenance": "الصيانة",
        "maintenanceType.repair": "الإصلاح",
        "maintenanceType.replacement": "الاستبدال",
        "maintenanceType.other": "أخرى",
        "maintenanceType.plannedMaintenance": "صيانة مخطط لها",
        "maintenanceType.oilChange": "تغيير الزيت",
        "maintenanceType.filterReplacement": "استبدال المرشحات",
        "maintenanceType.brakeReplacement": "استبدال الفرامل",
        "maintenanceType.tireReplacement": "استبدال الإطارات",
        "maintenanceType.diagnostics": "التشخيص",
        "maintenanceType.engineRepair": "إصلاح المحرك",
        "maintenanceType.transmissionRepair": "إصلاح ناقل الحركة",
        "maintenanceType.suspensionRepair": "إصلاح التعليق",
        "maintenanceType.brakeRepair": "إصلاح الفرامل",
        "maintenanceType.bodyRepair": "إصلاح الهيكل",
        "maintenanceType.electricalRepair": "إصلاح الكهرباء",
        
        // Fuel Types
        "fuelType.gasoline": "بنزين",
        "fuelType.diesel": "ديزل",
        "fuelType.hybrid": "هجين",
        "fuelType.electric": "كهربائي",
        "fuelType.gas": "غاز",
        "fuelType.gasGasoline": "غاز/بنزين",
        
        // Drive Types
        "driveType.front": "أمامي",
        "driveType.rear": "خلفي",
        "driveType.full": "كامل",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "يدوي",
        "transmission.automatic": "أوتوماتيكي",
        "transmission.robot": "روبوت",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "التقاط صورة",
        "photo.chooseFromGallery": "اختر من المعرض"
    ]
    
    // MARK: - Russian
    
    static let russian: [String: String] = [
        // Common
        "common.ok": "OK",
        "common.cancel": "Отмена",
        "common.save": "Сохранить",
        "common.delete": "Удалить",
        "common.edit": "Редактировать",
        "common.add": "Добавить",
        "common.close": "Закрыть",
        "common.back": "Назад",
        "common.next": "Далее",
        "common.done": "Готово",
        
        // Tab Bar
        "tabbar.chats": "Чаты",
        "tabbar.maintenance": "ТО",
        "tabbar.profile": "Профиль",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "Ваш помощник по автомобилям",
        "welcome.login": "Вход",
        "welcome.register": "Регистрация",
        
        // Settings
        "settings.profile": "Профиль",
        "settings.myCars": "Мои автомобили",
        "settings.noCars": "Нет сохранённых автомобилей",
        "settings.addCar": "Добавить авто",
        "settings.geolocation": "Геопозиция",
        "settings.autoDetermined": "Автоматически определено",
        "settings.determineLocation": "Определить местоположение",
        "settings.determining": "Определение...",
        "settings.appearance": "Внешний вид",
        "settings.theme": "Тема",
        "settings.lightTheme": "Светлая",
        "settings.darkTheme": "Темная",
        "settings.language": "Язык",
        "settings.account": "Аккаунт",
        "settings.logout": "Выйти",
        
        // Chat
        "chat.startDialog": "Начните диалог с ИИ-помощником",
        "chat.writeMessage": "Напишите сообщение...",
        "chat.generalQuestion": "General Question",
        "chat.checkEngine": "Check Engine",
        "chat.battery": "Battery",
        "chat.brakeSystem": "Brake System",
        "chat.engine": "Engine",
        "chat.transmission": "Transmission",
        "chat.suspension": "Suspension",
        "chat.electrical": "Electrical",
        "chat.acSystem": "AC System",
        "chat.tires": "Tires",
        "chat.chats": "Чаты",
        
        // Maintenance
        "maintenance.title": "ТО",
        "maintenance.noRecords": "Нет записей об обслуживании",
        "maintenance.addMaintenance": "Добавить ТО",
        "maintenance.upcomingServices": "Предстоящие сервисы",
        "maintenance.history": "История",
        "maintenance.addFirstRecord": "Добавить первую запись об обслуживании",
        
        // Car Input
        "carInput.addCar": "Добавить автомобиль",
        "carInput.brand": "Марка",
        "carInput.model": "Модель",
        "carInput.year": "Год",
        "carInput.engine": "Двигатель",
        "carInput.selectEngine": "Выберите двигатель",
        "carInput.additionalParams": "Дополнительные параметры",
        "carInput.fuelType": "Тип топлива",
        "carInput.driveType": "Привод",
        "carInput.transmission": "Коробка передач",
        "carInput.notSpecified": "Не указано",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (необязательно)",
        "carInput.additionalInfo": "Дополнительная информация",
        "carInput.notes": "Заметки, особенности, пожелания...",
        "carInput.addPhoto": "Добавить фото",
        "carInput.selectSource": "Выберите источник",
        "carInput.camera": "Камера",
        "carInput.gallery": "Галерея",
        "carInput.enterBrandFirst": "Сначала введите марку",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "Редактировать ТО",
        "maintenanceInput.dateAndMileage": "Дата и пробег",
        "maintenanceInput.maintenanceDate": "Дата ТО",
        "maintenanceInput.plannedDate": "Дата запланированной работы",
        "maintenanceInput.workDate": "Дата работ",
        "maintenanceInput.mileage": "Пробег (км)",
        "maintenanceInput.works": "Работы",
        "maintenanceInput.selectType": "Выберите тип",
        "maintenanceInput.description": "Описание",
        "maintenanceInput.worksDescription": "Описание работ",
        "maintenanceInput.performedWorks": "Выполненные работы",
        "maintenanceInput.performedWorksList": "Список выполненных работ",
        "maintenanceInput.document": "Документ (чек/наряд)",
        "maintenanceInput.attachPhoto": "Прикрепить фото",
        "maintenanceInput.deletePhoto": "Удалить фото",
        "maintenanceInput.analyzing": "Анализ...",
        "maintenanceInput.textRecognized": "Текст распознан",
        "maintenanceInput.recognizedText": "Распознанный текст",
        "maintenanceInput.useRecognizedText": "Использовать распознанный текст",
        "maintenanceInput.plannedWork": "Запланированная работа",
        "maintenanceInput.addType": "Добавить",
        "maintenanceInput.addTypeName": "Название типа",
        "maintenanceInput.addMaintenanceType": "Добавить тип ТО",
        "maintenanceInput.addRepairType": "Добавить тип ремонта",
        "maintenanceInput.enterMaintenanceType": "Введите название нового типа ТО",
        "maintenanceInput.enterRepairType": "Введите название нового типа ремонта",
        "maintenanceInput.describeWorkType": "Опишите тип работы",
        "maintenanceInput.addWorkType": "Добавить тип работы",
        "maintenanceInput.enterWorkTypeName": "Введите название типа работы",
        "maintenanceInput.overdue": "Просрочено на",
        "maintenanceInput.days": "дн.",
        "maintenanceInput.in": "Через",
        "maintenanceInput.mileageLabel": "Пробег:",
        "maintenanceInput.documentAttached": "Документ прикреплен",
        
        // Car Management
        "carInput.editCar": "Редактировать авто",
        "carInput.myCars": "Мои автомобили",
        "carInput.addFirstCar": "Добавьте первый автомобиль",
        
        // Maintenance Types
        "maintenanceType.maintenance": "ТО",
        "maintenanceType.repair": "Ремонт",
        "maintenanceType.replacement": "Замена",
        "maintenanceType.other": "Другое",
        "maintenanceType.plannedMaintenance": "Плановое ТО",
        "maintenanceType.oilChange": "Замена масла",
        "maintenanceType.filterReplacement": "Замена фильтров",
        "maintenanceType.brakeReplacement": "Замена тормозов",
        "maintenanceType.tireReplacement": "Замена шин",
        "maintenanceType.diagnostics": "Диагностика",
        "maintenanceType.engineRepair": "Ремонт двигателя",
        "maintenanceType.transmissionRepair": "Ремонт коробки передач",
        "maintenanceType.suspensionRepair": "Ремонт подвески",
        "maintenanceType.brakeRepair": "Ремонт тормозов",
        "maintenanceType.bodyRepair": "Ремонт кузова",
        "maintenanceType.electricalRepair": "Ремонт электрики",
        
        // Fuel Types
        "fuelType.gasoline": "Бензин",
        "fuelType.diesel": "Дизель",
        "fuelType.hybrid": "Гибрид",
        "fuelType.electric": "Электрический",
        "fuelType.gas": "Газ",
        "fuelType.gasGasoline": "Газ/Бензин",
        
        // Drive Types
        "driveType.front": "Передний",
        "driveType.rear": "Задний",
        "driveType.full": "Полный",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "Механическая",
        "transmission.automatic": "Автоматическая",
        "transmission.robot": "Робот",
        "transmission.cvt": "Вариатор",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "Сделать фото",
        "photo.chooseFromGallery": "Выбрать из галереи"
    ]
    
    // MARK: - Portuguese
    
    static let portuguese: [String: String] = [
        // Common
        "common.ok": "OK",
        "common.cancel": "Cancelar",
        "common.save": "Salvar",
        "common.delete": "Excluir",
        "common.edit": "Editar",
        "common.add": "Adicionar",
        "common.close": "Fechar",
        "common.back": "Voltar",
        "common.next": "Próximo",
        "common.done": "Concluído",
        
        // Tab Bar
        "tabbar.chats": "Chats",
        "tabbar.maintenance": "Manutenção",
        "tabbar.profile": "Perfil",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "Seu assistente de carros",
        "welcome.login": "Entrar",
        "welcome.register": "Registrar",
        
        // Settings
        "settings.profile": "Perfil",
        "settings.myCars": "Meus Carros",
        "settings.noCars": "Nenhum carro salvo",
        "settings.addCar": "Adicionar Carro",
        "settings.geolocation": "Geolocalização",
        "settings.autoDetermined": "Determinado automaticamente",
        "settings.determineLocation": "Determinar localização",
        "settings.determining": "Determinando...",
        "settings.appearance": "Aparência",
        "settings.theme": "Tema",
        "settings.lightTheme": "Claro",
        "settings.darkTheme": "Escuro",
        "settings.language": "Idioma",
        "settings.account": "Conta",
        "settings.logout": "Sair",
        
        // Chat
        "chat.startDialog": "Inicie um diálogo com o assistente de IA",
        "chat.writeMessage": "Escreva uma mensagem...",
        "chat.generalQuestion": "Pergunta Geral",
        "chat.checkEngine": "Verificar Motor",
        "chat.battery": "Bateria",
        "chat.brakeSystem": "Sistema de Freios",
        "chat.engine": "Motor",
        "chat.transmission": "Transmissão",
        "chat.suspension": "Suspensão",
        "chat.electrical": "Elétrico",
        "chat.acSystem": "Sistema de Ar Condicionado",
        "chat.tires": "Pneus",
        "chat.chats": "Chats",
        
        // Maintenance
        "maintenance.title": "Manutenção",
        "maintenance.noRecords": "Nenhum registro de manutenção",
        "maintenance.addMaintenance": "Adicionar Manutenção",
        "maintenance.upcomingServices": "Serviços Próximos",
        "maintenance.history": "Histórico",
        "maintenance.addFirstRecord": "Adicionar primeiro registro de manutenção",
        
        // Car Input
        "carInput.addCar": "Adicionar Carro",
        "carInput.brand": "Marca",
        "carInput.model": "Modelo",
        "carInput.year": "Ano",
        "carInput.engine": "Motor",
        "carInput.selectEngine": "Selecionar motor",
        "carInput.additionalParams": "Parâmetros Adicionais",
        "carInput.fuelType": "Tipo de Combustível",
        "carInput.driveType": "Tipo de Tração",
        "carInput.transmission": "Transmissão",
        "carInput.notSpecified": "Não especificado",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (opcional)",
        "carInput.additionalInfo": "Informações Adicionais",
        "carInput.notes": "Notas, características, desejos...",
        "carInput.addPhoto": "Adicionar Foto",
        "carInput.selectSource": "Selecionar Fonte",
        "carInput.camera": "Câmera",
        "carInput.gallery": "Galeria",
        "carInput.enterBrandFirst": "Digite a marca primeiro",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "Editar Manutenção",
        "maintenanceInput.dateAndMileage": "Data e Quilometragem",
        "maintenanceInput.maintenanceDate": "Data de Manutenção",
        "maintenanceInput.plannedDate": "Data de Trabalho Planejado",
        "maintenanceInput.workDate": "Data de Trabalho",
        "maintenanceInput.mileage": "Quilometragem (km)",
        "maintenanceInput.works": "Trabalhos",
        "maintenanceInput.selectType": "Selecionar tipo",
        "maintenanceInput.description": "Descrição",
        "maintenanceInput.worksDescription": "Descrição do trabalho",
        "maintenanceInput.performedWorks": "Trabalhos Realizados",
        "maintenanceInput.performedWorksList": "Lista de trabalhos realizados",
        "maintenanceInput.document": "Documento (recibo/ordem de serviço)",
        "maintenanceInput.attachPhoto": "Anexar Foto",
        "maintenanceInput.deletePhoto": "Excluir Foto",
        "maintenanceInput.analyzing": "Analisando...",
        "maintenanceInput.textRecognized": "Texto reconhecido",
        "maintenanceInput.recognizedText": "Texto Reconhecido",
        "maintenanceInput.useRecognizedText": "Usar Texto Reconhecido",
        "maintenanceInput.plannedWork": "Trabalho Planejado",
        "maintenanceInput.addType": "Adicionar",
        "maintenanceInput.addTypeName": "Nome do tipo",
        "maintenanceInput.addMaintenanceType": "Adicionar Tipo de Manutenção",
        "maintenanceInput.addRepairType": "Adicionar Tipo de Reparo",
        "maintenanceInput.enterMaintenanceType": "Digite o nome do novo tipo de manutenção",
        "maintenanceInput.enterRepairType": "Digite o nome do novo tipo de reparo",
        "maintenanceInput.describeWorkType": "Descrever tipo de trabalho",
        "maintenanceInput.addWorkType": "Adicionar tipo de trabalho",
        "maintenanceInput.enterWorkTypeName": "Digite o nome do tipo de trabalho",
        "maintenanceInput.overdue": "Atrasado por",
        "maintenanceInput.days": "dias",
        "maintenanceInput.in": "Em",
        "maintenanceInput.mileageLabel": "Quilometragem:",
        "maintenanceInput.documentAttached": "Documento anexado",
        
        // Car Management
        "carInput.editCar": "Editar Carro",
        "carInput.myCars": "Meus Carros",
        "carInput.addFirstCar": "Adicionar primeiro carro",
        
        // Maintenance Types
        "maintenanceType.maintenance": "Manutenção",
        "maintenanceType.repair": "Reparo",
        "maintenanceType.replacement": "Substituição",
        "maintenanceType.other": "Outro",
        "maintenanceType.plannedMaintenance": "Manutenção Planejada",
        "maintenanceType.oilChange": "Troca de Óleo",
        "maintenanceType.filterReplacement": "Substituição de Filtros",
        "maintenanceType.brakeReplacement": "Substituição de Freios",
        "maintenanceType.tireReplacement": "Substituição de Pneus",
        "maintenanceType.diagnostics": "Diagnóstico",
        "maintenanceType.engineRepair": "Reparo do Motor",
        "maintenanceType.transmissionRepair": "Reparo da Transmissão",
        "maintenanceType.suspensionRepair": "Reparo da Suspensão",
        "maintenanceType.brakeRepair": "Reparo de Freios",
        "maintenanceType.bodyRepair": "Reparo da Carroceria",
        "maintenanceType.electricalRepair": "Reparo Elétrico",
        
        // Fuel Types
        "fuelType.gasoline": "Gasolina",
        "fuelType.diesel": "Diesel",
        "fuelType.hybrid": "Híbrido",
        "fuelType.electric": "Elétrico",
        "fuelType.gas": "Gás",
        "fuelType.gasGasoline": "Gás/Gasolina",
        
        // Drive Types
        "driveType.front": "Dianteiro",
        "driveType.rear": "Traseiro",
        "driveType.full": "Integral",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "Manual",
        "transmission.automatic": "Automática",
        "transmission.robot": "Robô",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "Tirar Foto",
        "photo.chooseFromGallery": "Escolher da Galeria"
    ]
    
    // MARK: - Indonesian
    
    static let indonesian: [String: String] = [
        // Common
        "common.ok": "OK",
        "common.cancel": "Batal",
        "common.save": "Simpan",
        "common.delete": "Hapus",
        "common.edit": "Edit",
        "common.add": "Tambah",
        "common.close": "Tutup",
        "common.back": "Kembali",
        "common.next": "Berikutnya",
        "common.done": "Selesai",
        
        // Tab Bar
        "tabbar.chats": "Chat",
        "tabbar.maintenance": "Perawatan",
        "tabbar.profile": "Profil",
        
        // Welcome
        "welcome.title": "CarAssistant",
        "welcome.subtitle": "Asisten mobil Anda",
        "welcome.login": "Masuk",
        "welcome.register": "Daftar",
        
        // Settings
        "settings.profile": "Profil",
        "settings.myCars": "Mobil Saya",
        "settings.noCars": "Tidak ada mobil tersimpan",
        "settings.addCar": "Tambah Mobil",
        "settings.geolocation": "Geolokasi",
        "settings.autoDetermined": "Ditentukan secara otomatis",
        "settings.determineLocation": "Tentukan lokasi",
        "settings.determining": "Menentukan...",
        "settings.appearance": "Tampilan",
        "settings.theme": "Tema",
        "settings.lightTheme": "Terang",
        "settings.darkTheme": "Gelap",
        "settings.language": "Bahasa",
        "settings.account": "Akun",
        "settings.logout": "Keluar",
        
        // Chat
        "chat.startDialog": "Mulai dialog dengan asisten AI",
        "chat.writeMessage": "Tulis pesan...",
        "chat.generalQuestion": "Pertanyaan Umum",
        "chat.checkEngine": "Periksa Mesin",
        "chat.battery": "Baterai",
        "chat.brakeSystem": "Sistem Rem",
        "chat.engine": "Mesin",
        "chat.transmission": "Transmisi",
        "chat.suspension": "Suspensi",
        "chat.electrical": "Listrik",
        "chat.acSystem": "Sistem AC",
        "chat.tires": "Ban",
        "chat.chats": "Chat",
        
        // Maintenance
        "maintenance.title": "Perawatan",
        "maintenance.noRecords": "Tidak ada catatan perawatan",
        "maintenance.addMaintenance": "Tambah Perawatan",
        "maintenance.upcomingServices": "Layanan Mendatang",
        "maintenance.history": "Riwayat",
        "maintenance.addFirstRecord": "Tambah catatan perawatan pertama",
        
        // Car Input
        "carInput.addCar": "Tambah Mobil",
        "carInput.brand": "Merek",
        "carInput.model": "Model",
        "carInput.year": "Tahun",
        "carInput.engine": "Mesin",
        "carInput.selectEngine": "Pilih mesin",
        "carInput.additionalParams": "Parameter Tambahan",
        "carInput.fuelType": "Jenis Bahan Bakar",
        "carInput.driveType": "Jenis Penggerak",
        "carInput.transmission": "Transmisi",
        "carInput.notSpecified": "Tidak ditentukan",
        "carInput.vin": "VIN",
        "carInput.vinOptional": "VIN (opsional)",
        "carInput.additionalInfo": "Informasi Tambahan",
        "carInput.notes": "Catatan, fitur, keinginan...",
        "carInput.addPhoto": "Tambah Foto",
        "carInput.selectSource": "Pilih Sumber",
        "carInput.camera": "Kamera",
        "carInput.gallery": "Galeri",
        "carInput.enterBrandFirst": "Masukkan merek terlebih dahulu",
        
        // Maintenance Input
        "maintenanceInput.editMaintenance": "Edit Perawatan",
        "maintenanceInput.dateAndMileage": "Tanggal dan Jarak Tempuh",
        "maintenanceInput.maintenanceDate": "Tanggal Perawatan",
        "maintenanceInput.plannedDate": "Tanggal Pekerjaan Terencana",
        "maintenanceInput.workDate": "Tanggal Pekerjaan",
        "maintenanceInput.mileage": "Jarak Tempuh (km)",
        "maintenanceInput.works": "Pekerjaan",
        "maintenanceInput.selectType": "Pilih jenis",
        "maintenanceInput.description": "Deskripsi",
        "maintenanceInput.worksDescription": "Deskripsi pekerjaan",
        "maintenanceInput.performedWorks": "Pekerjaan yang Dilakukan",
        "maintenanceInput.performedWorksList": "Daftar pekerjaan yang dilakukan",
        "maintenanceInput.document": "Dokumen (tanda terima/perintah kerja)",
        "maintenanceInput.attachPhoto": "Lampirkan Foto",
        "maintenanceInput.deletePhoto": "Hapus Foto",
        "maintenanceInput.analyzing": "Menganalisis...",
        "maintenanceInput.textRecognized": "Teks dikenali",
        "maintenanceInput.recognizedText": "Teks yang Dikenali",
        "maintenanceInput.useRecognizedText": "Gunakan Teks yang Dikenali",
        "maintenanceInput.plannedWork": "Pekerjaan Terencana",
        "maintenanceInput.addType": "Tambah",
        "maintenanceInput.addTypeName": "Nama jenis",
        "maintenanceInput.addMaintenanceType": "Tambah Jenis Perawatan",
        "maintenanceInput.addRepairType": "Tambah Jenis Perbaikan",
        "maintenanceInput.enterMaintenanceType": "Masukkan nama jenis perawatan baru",
        "maintenanceInput.enterRepairType": "Masukkan nama jenis perbaikan baru",
        "maintenanceInput.describeWorkType": "Jelaskan jenis pekerjaan",
        "maintenanceInput.addWorkType": "Tambah jenis pekerjaan",
        "maintenanceInput.enterWorkTypeName": "Masukkan nama jenis pekerjaan",
        "maintenanceInput.overdue": "Terlambat",
        "maintenanceInput.days": "hari",
        "maintenanceInput.in": "Dalam",
        "maintenanceInput.mileageLabel": "Jarak Tempuh:",
        "maintenanceInput.documentAttached": "Dokumen dilampirkan",
        
        // Car Management
        "carInput.editCar": "Edit Mobil",
        "carInput.myCars": "Mobil Saya",
        "carInput.addFirstCar": "Tambah mobil pertama",
        
        // Maintenance Types
        "maintenanceType.maintenance": "Perawatan",
        "maintenanceType.repair": "Perbaikan",
        "maintenanceType.replacement": "Penggantian",
        "maintenanceType.other": "Lainnya",
        "maintenanceType.plannedMaintenance": "Perawatan Terencana",
        "maintenanceType.oilChange": "Ganti Oli",
        "maintenanceType.filterReplacement": "Ganti Filter",
        "maintenanceType.brakeReplacement": "Ganti Rem",
        "maintenanceType.tireReplacement": "Ganti Ban",
        "maintenanceType.diagnostics": "Diagnostik",
        "maintenanceType.engineRepair": "Perbaikan Mesin",
        "maintenanceType.transmissionRepair": "Perbaikan Transmisi",
        "maintenanceType.suspensionRepair": "Perbaikan Suspensi",
        "maintenanceType.brakeRepair": "Perbaikan Rem",
        "maintenanceType.bodyRepair": "Perbaikan Body",
        "maintenanceType.electricalRepair": "Perbaikan Listrik",
        
        // Fuel Types
        "fuelType.gasoline": "Bensin",
        "fuelType.diesel": "Solar",
        "fuelType.hybrid": "Hibrida",
        "fuelType.electric": "Listrik",
        "fuelType.gas": "Gas",
        "fuelType.gasGasoline": "Gas/Bensin",
        
        // Drive Types
        "driveType.front": "Depan",
        "driveType.rear": "Belakang",
        "driveType.full": "Penuh",
        "driveType.fourWD": "4WD",
        "driveType.aws": "AWD",
        
        // Transmission Types
        "transmission.manual": "Manual",
        "transmission.automatic": "Otomatis",
        "transmission.robot": "Robot",
        "transmission.cvt": "CVT",
        "transmission.dsg": "DSG",
        "transmission.dct": "DCT",
        
        // Photo Selection
        "photo.takePhoto": "Ambil Foto",
        "photo.chooseFromGallery": "Pilih dari Galeri"
    ]
}

